name: Analyze and Testing

on:
  push:
    branches:
      - feature-*

  pull_request:
    branches:
      - main
      - version-*

jobs:
  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.3'
          channel: 'stable'
          architecture: x64
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Generate code
        run: dart run build_runner build
      - name: Analyze code
        run: dart analyze .
  widget-tests:
    name: widget-tests
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.3'
          channel: 'stable'
          architecture: x64
      - name: Generate code
        run: dart run build_runner build
      - name: Run tests
        run: flutter test
